#!/usr/bin/env ruby

#provided_branches

FORBIDDEN_BRANCHES=PROVIDED_BRANCHES.split(',')


def merge?
  ARGV[1] == "merge"
end

def merge_msg
  @msg ||= `cat .git/MERGE_MSG`
end

def from_branch
  @is_merge_commit = merge_msg.match(/Merge branch '(.*?)'/)
  if @is_merge_commit
    @from_branch = merge_msg.match(/Merge branch '(.*?)'/)[1]
  else
    return true
  end
end

def current_branch
  return `git symbolic-ref --short HEAD`
end

def from_forbidden_branch?
  FORBIDDEN_BRANCHES.include?(from_branch)
end

if merge? && from_forbidden_branch? && !FORBIDDEN_BRANCHES.include?("#{current_branch}".strip)
  puts
  puts "\033[31m ATTENTION!! Merge prevented"
  puts
  puts "\033[39m You are trying to merge #{from_branch} into your branch #{current_branch}."
  puts
  puts "\033[39m RUN `git reset --merge` to abort this merge"
  puts
  exit 1
end
