#!/usr/bin/env ruby

#provided_branches

FORBIDDEN_BRANCHES=PROVIDED_BRANCHES.split(',')

def merge?
  ARGV[1] == "merge"
end

def merge_msg
  @msg ||= `cat .git/MERGE_MSG`
end

def from_branch
  @from_branch = merge_msg.match(/Merge branch '(.*?)'/)[1]
end

def from_forbidden_branch?
  FORBIDDEN_BRANCHES.include?(from_branch)
end

if merge? && from_forbidden_branch?
  puts
  puts "\033[31m ATTENTION!! Merge prevented"
  puts
  puts "\033[39m You are trying to merge #{from_branch} into your branch."
  puts
  puts "\033[39m RUN `git reset --merge` to abort this merge"
  puts
  exit 1
end
